### ISSUE TITLE
Beginner Friendly Terms

### ISSUE THREAD

**Issue by 4mber** [OpenMined/OM-Welcome-Package#26]
1 - Alphabetize the terms
2 - Add Table of Contents

**Comment by darigovresearch** [comment]
With respect to the table of contents:
- did you want a table of content for the sections or for each specific word as well?
- The current table of contents is probably the best way of doing it now but just wanted to confirm this

With respect to the Alphabetising the terms:
- Did you want to sort the sections first alphabetically and then alphabetise terms within each section?
- Or do you have a preferred order for the sections?

Happy to take a look at resolving this issue

**Comment by 4mber** [comment]
Hey @darigovresearch ! So sorry, just saw this - I think the current TOC is probably fine, as well as the order of the sections. We just need to alphabetise the words within each section.

**Comment by darigovresearch** [comment]
Hey @4mber! No worries at all, I have made the relevant changes to the .md file and is now in a pull request (#56) which would resolve this issue if merged!

**Comment by 4mber** [comment]
Awesome, thanks!!
