### ISSUE TITLE
Team Relevant Blog Posts

### ISSUE THREAD

**Issue by 4mber** [OpenMined/OM-Welcome-Package#29]
Add all team relevant blog posts from blog.openmined.org to their individual sections on their team category pages.

**Comment by Boluwatifeh** [comment]
@4mber I'd love to work on this. There are posts under different team groups (federated learning, differential privacy) and some not under a team on the openmined blog. Should i add the content by unique posts or by "filed under". What do you suggest?

**Comment by 4mber** [comment]
@Boluwatifeh Great question!

There are SO many posts, and I'm sure a lot of them have something to do with a team. So maybe go through each category, add the ones that there are already categories for to their related team, then scan through the ones that aren't categorised to see if they should be connected to any specific team (for instance, I know there are a few to do with the Learning Team, announcing the team and the beta-bootcamp, and there may be other uncategorised ones like that as well).

Does that make sense?

Just going to tag in @em-blue as well, as she leads the writing team and may be able to help in some capacity.

The idea is just that, we have info for each team on the Dev and Community Team pages in this repo, and we just want to add a section for each team including links to related OM blog posts, if they exist, so people can read more about each team and see what the team has worked on, if they've written about it.

**Comment by Boluwatifeh** [comment]
Alright, sounds doable. Working on it

**Comment by em-blue** [comment]
@Boluwatifeh Great idea - and if you feel up to it, I could give you temporary editor permissions on our blog so you could go through and tag previous blog posts with whichever tags you think fit them. Our tagging hasn't been very thorough, some blogs don't have any tags

**Comment by Boluwatifeh** [comment]
@em-blue that would be great as the tags would also serve as a base guide for future blog posts

**Comment by 4mber** [comment]
Ooh great idea guys!! :raised_hands:

**Comment by Boluwatifeh** [comment]
made the changes to reflect relevant blog posts for each team  @4mber kindly look into [this PR](https://github.com/OpenMined/OM-Welcome-Package/pull/59) so i can send the PR for this particular issue thanks.

**Comment by 4mber** [comment]
Perfect, thanks so much @Boluwatifeh ! :)
