### ISSUE TITLE
Federated Learning Teams Update

### ISSUE THREAD

**Issue by 4mber** [OpenMined/OM-Welcome-Package#58]
Currently on the [development teams page](https://github.com/OpenMined/OM-Welcome-Package/blob/master/Development-Teams.md), we still have the Grid Team and Web and Mobile Team listed, however these have been incorporated into the newly formed Federated Learning Team.

The Federated Learning Team only has a brief description: _"The Federated Learning Team is a new team which combines the Web & Mobile Team, the Grid Team, and two new teams: Workers Team, and RecSys Team. More details are coming soon, but in the meantime contact the team lead below for more information."_

But what we need is the full Federated Learning Team info (like all of the other teams), which should include information about the sub-teams mentioned above.

**Comment by cereallarceny** [comment]
@4mber here you go!

**Federated Learning**
_Building federated learning into the OM ecosystem through libraries available in Kotlin, Swift, Javascript, and Python. Manages a series of worker libraries in multiple languages and modalities, as well as the PyGrid central server for federated learning and remote data science._

**Team Lead:** [Patrick Cason](https://github.com/cereallarceny)
**Team Members:** No current list
**Team Roadmap:** Data-centrc (_coming soon_) and [Model-centric](https://github.com/OpenMined/Roadmap/blob/master/federated_learning/projects/model_centric_fl.md)
**Good First Issues:** [PyGrid](https://github.com/OpenMined/PyGrid/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue+%3Amortar_board%3A%22), [syft.js](https://github.com/OpenMined/syft.js/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue+%3Amortar_board%3A%22), [KotlinSyft](https://github.com/OpenMined/KotlinSyft/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue+%3Amortar_board%3A%22), [SwiftSyft](https://github.com/OpenMined/SwiftSyft/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue+%3Amortar_board%3A%22), [Threepio](https://github.com/OpenMined/Threepio/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue+%3Amortar_board%3A%22)

**Requirements/Recommendations to Join:**
- You have already merged at least 1 pull request to an OpenMined GitHub repository (see Good First Issues above), particularly a Javascript-related issue
- You have contributed before to OpenMined's numerous repos
- You have experience working with Javascript
- You have experience working with socket servers
- You have experience working with WebRTC
- You have experience with dev ops, including cloud deployment, scaling, and load-balancing
- You have experience working in native mobile development including the Kotlin, Java, Swift, and Objective-C languages

**Accepting New Members:** YES
[Application to Join](https://forms.gle/V1EWWST1pfbT5c2b9)

**Comment by 4mber** [comment]
Thanks @cereallarceny !! Could you change [the markdown file here](https://github.com/OpenMined/OM-Welcome-Package/blob/master/Development-Teams.md), and submit as a PR please? Thanks! :)

**Comment by cereallarceny** [comment]
Done.
