### ISSUE TITLE
Links to Openmined Slack signup broken everywhere!

### ISSUE THREAD

**Issue by itsallonetome** [OpenMined/OM-Welcome-Package#64]
## Description
All the links to join the openmined slack channel are broken.  Slack says "no longer valid"

## How to Reproduce
1. Go to any openmined website (or this welcome package)
2. Click on join slack

## Expected Behavior
Get signup page for openmined on slack.

**Comment by abhaysjuneja** [comment]
Came here for this. Saw it's been reported only 5 hours ago. Hopefully a new link will be generated soon. Waiting ...

**Comment by Siddhant-K-code** [comment]
I guess, All Fine Now! Maintainers Can Close this issue now.D
