### ISSUE TITLE
Request for joining the organisation.

### ISSUE THREAD

**Issue by akshitagupta15june** [OpenMined/OM-Welcome-Package#65]
## What?
Describe as briefly as possible what you'd like to research

## How long?
Research is an incredibly important aspect of software development. How long do you think it should take to research until you're ready to begin implementation?

**Comment by 4mber** [comment]
Going to close this now, as it's been inactive for a long while, but @akshitagupta15june - if you still have questions about research, I'd recommend reaching out on our [Slack](slack.openmined.org), in the research channel
