### ISSUE TITLE
Change team members names to GitHub profile links

### ISSUE THREAD

**Issue by 4mber** [OpenMined/OM-Welcome-Package#7]
Change all team member names to link to their GitHub profiles on all team pages where member names are currently listed with Slack handles.

**Comment by Boluwatifeh** [comment]
hi @4mber i would love to take on this issue and also i feel collecting the different team member github names and slack username via a google form in order to cross reference them where necessary would be great.

**Comment by 4mber** [comment]
Hi @Boluwatifeh ! Sorry I'm just seeing this now!

I don't think we actually need a Google form, you should be able to search for each person on Slack, then either 1) their GitHub handle will be listed in their profile, or 2) you can use their full name listed in their Slack profile to check for them on GitHub and just make sure the people in the profile pictures are the same.

Then if there are any you can't find on GitHub, you could reach out to the individual team leads on Slack to ask for their GitHub.

(I think if you ask all of the team leads to fill out a Google Form for this, it will likely take a looong time to get everyone's response because they're super busy with a million other things - the way I listed above will probably be a lot faster and easier all around!)

Thanks so much for offering to help on this!! :)

**Comment by Boluwatifeh** [comment]
Alright, working on it right away!

**Comment by Boluwatifeh** [comment]
Done, merging the [#57](https://github.com/OpenMined/OM-Welcome-Package/pull/57)  PR would resolve this issue kindly check it out @4mber

**Comment by 4mber** [comment]
Perfect, thank!! :)
